In [2]:
import pandas as pd

In [3]:
data = [["harry",34],["jill",67],["jacob",67],["shubbh",67]]

In [4]:
data

[['harry', 34], ['jill', 67], ['jacob', 67], ['shubbh', 67]]

In [5]:
pd.DataFrame(data,columns=["Name", "Marks"])

     Name  Marks
0   harry     34
1    jill     67
2   jacob     67
3  shubbh     67

In [6]:
data = {"a":[4,5,6],"b":[7,8,9]}

In [7]:
data

{'a': [4, 5, 6], 'b': [7, 8, 9]}

In [8]:
df = pd.DataFrame(data)

In [9]:
df

   a  b
0  4  7
1  5  8
2  6  9

In [10]:
df=pd.read_excel("data.xlsx")

In [11]:
df

      Name School  Marks
0  Shubham   ASOB     35
1   Joshua    VPS     56
2  Krishna   Urmi     85
3   Adarsh     KV     45
4     raju     KV     78
5     john    BBL     75
6       kk    lps     12

In [12]:
df = pd.read_csv("data.csv")

In [13]:
df

      Name School  Marks
0  Shubham   ASOB     35
1   Joshua    VPS     56
2  Krishna   Urmi     85
3   Adarsh     KV     45
4     raju     KV     78
5     john    BBL     75
6       kk    lps     12

In [17]:
df = pd.read_json("data.json")

In [18]:
df

      name    lang
0  Krishna  python
1      Kri    JAVA

In [20]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [21]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [23]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [25]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [27]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [28]:
df.shape

(244, 7)