In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("bollywood.csv")

In [11]:
df

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Sushant Singh Rajput,MS Dhoni,2014,Biopic,900,9.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [12]:
df.sort_values("BoxOffice(Cr)")

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Sushant Singh Rajput,MS Dhoni,2014,Biopic,900,9.1
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [13]:
df.sort_values("BoxOffice(Cr)",ascending=False)

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
10,Sushant Singh Rajput,MS Dhoni,2014,Biopic,900,9.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3

In [25]:
df2 = df.sort_values("BoxOffice(Cr)",ascending=False).copy()

In [26]:
#df2.reset_index(drop = True, inplace=True)

In [27]:
df2

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
10,Sushant Singh Rajput,MS Dhoni,2014,Biopic,900,9.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3

In [28]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Sushant Singh Rajput,MS Dhoni,2014,Biopic,900,9.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [31]:
df2["Rank"] = df2["BoxOffice(Cr)"].rank(ascending=False)

In [34]:
df2

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,2.0
10,Sushant Singh Rajput,MS Dhoni,2014,Biopic,900,9.1,3.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,4.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,5.0
7,Hrithik Roshan,War,2019,Action,475,6.5,6.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,8.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,9.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,11.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,12.0

In [37]:
df2 = df2 [["Film","Actor","Year","Genre","IMDb","BoxOffice(Cr)"]]

In [38]:
df2

,Film,Actor,Year,Genre,IMDb,BoxOffice(Cr)
2,Dangal,Aamir Khan,2016,Biography,8.4,2024
0,Pathaan,Shah Rukh Khan,2023,Action,7.2,1050
10,MS Dhoni,Sushant Singh Rajput,2014,Biopic,9.1,900
4,Padmaavat,Ranveer Singh,2018,Historical,7.0,585
1,Tiger Zinda Hai,Salman Khan,2017,Action,6.0,565
7,War,Hrithik Roshan,2019,Action,6.5,475
3,Brahmastra,Ranbir Kapoor,2022,Fantasy,5.6,431
11,Uri: The Surgical Strike,Vicky Kaushal,2019,Action,8.2,342
8,Good Newwz,Akshay Kumar,2019,Comedy,7.0,318
9,Bhool Bhulaiyaa 2,Kartik Aaryan,2022,Horror Comedy,5.9,266
6,Stree,Rajkummar Rao,2018,Horror Comedy,7.5,180
5,Andhadhun,Ayushmann Khurrana,2018,Thriller,8.3,111